### ISSUE TITLE
poetry deps issue on macos

### ISSUE THREAD

**Issue by igorclark** [dreamingspires/EPIONCHO-IBM#17]
hiya - running on macos 12.6.2 (monterey) i get this fresh out of the repo on branch `epioncho-improvements`:

```
[igor@igors-mac-mini]$ python3 -V
Python 3.10.9
[igor@igors-mac-mini]$ poetry --version
Poetry (version 1.3.1)
[igor@igors-mac-mini]$ poetry install
The currently activated Python version 3.11.1 is not supported by the project (>=3.9, <3.11).
Trying to find and use a compatible version.
Using python3 (3.10.9)
Installing dependencies from lock file

The current project's Python requirement (3.11.1) is not compatible with some of the required packages Python requirement:
  - fast-binomial requires Python >=3.9, <3.11, so it will not be satisfied for Python 3.11.1

Because epioncho-ibm depends on fast-binomial (0.1.0) @ git+ssh://git@github.com/dreamingspires/fast-binomial.git@HEAD which requires Python >=3.9, <3.11, version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For fast-binomial, a possible solution would be to set the `python` property to "<empty>"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
[igor@igors-mac-mini]$ poetry lock --check
The currently activated Python version 3.11.1 is not supported by the project (>=3.9, <3.11).
Trying to find and use a compatible version.
Using python3 (3.10.9)
poetry.lock is consistent with pyproject.toml.
```

so that doesn't work, which seems weird because there are conflicts in the versions of python it's talking about ("activated" = `3.11.1`, "using" = `3.10.9`).

on my MBP laptop i removed `poetry.lock` and tried again, which worked, but on my mac mini it doesn't work. as far as i can tell they're on the same OS/python3 versions, i.e. `12.6.2` and `3.10.9` from homebrew, only difference being that MBP is apple m1 vs mac mini being x86_64. oh and `/usr/local/bin/python` on the x86/mac mini is symlink to `/usr/local/bin/python3` whereas `/opt/homebrew/bin/python` doesn't exist on the MBP.

any ideas? thanks!

cheers!
i

**Comment by mark-todd** [comment]
Hi Igor,

Thanks for this - it seems like there's some of mismatch in python version for epioncho and some of its dependencies - I'll set them all to be >=3.10, <4.0 and that should fix it - thanks for letting us know!

Cheers,
Mark

**Comment by mark-todd** [comment]
Resolved with this I think https://github.com/dreamingspires/EPIONCHO-IBM/pull/18
