### ISSUE TITLE
Python 3.10 only?

### ISSUE THREAD

**Issue by tlestang** [dreamingspires/EPIONCHO-IBM#62]
I'd like to run some of the examples in `examples` to test #60 but I have python 3.11 installed. It's the packaged python 3 in Debian stable. I'm curious what is the reason behind the restriction to python 3.10?

I tried to build [fast-binomial](https://github.com/dreamingspires/fast-binomial) but ended up with compilation errors related to `PyFrameObject` (as reported [here](https://github.com/pybind/pybind11/discussions/4333)). Is that the reason?

Bit of a hassle to have to build/install another Python just to run the model, that's all.

**Comment by mark-todd** [comment]
Yes this is the reason - we had issues with fast binomial compiling in some OSs with 3.11, so I made it use 3.10 only. You can switch to 3.10 in poetry though - you just need to install it as well as 3.11 .
